# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('sourceId', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=64, null=True)),
                ('tosId', models.IntegerField(db_index=True, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('adminLevel', models.IntegerField(default=1)),
                ('name_cn', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Tutorial.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationSubCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityId', models.CharField(max_length=32)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subCities', to='Tutorial.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='Tutorial.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Dida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryFile', models.FilePathField(null=True)),
                ('cityFile', models.FilePathField(null=True)),
                ('hotelFile', models.FilePathField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('sourceId', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=64, null=True)),
                ('tosId', models.IntegerField(db_index=True, null=True)),
                ('name_en', models.CharField(max_length=128)),
                ('name_cn', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('zipCode', models.CharField(max_length=32, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('geohash8', models.CharField(max_length=16, null=True)),
                ('starRating', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=128, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='Tutorial.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='HotelUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='Tutorial.Hotel')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='hotel',
            index_together=set([('destination', 'source')]),
        ),
    ]
