# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('sourceId', models.CharField(max_length=32, null=True)),
                ('countryCode', models.CharField(max_length=16, null=True)),
                ('version', models.CharField(max_length=64, null=True)),
                ('tosId', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('name_cn', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('sourceId', models.CharField(max_length=32, null=True)),
                ('countryCode', models.CharField(max_length=16, null=True)),
                ('subCities', models.TextField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('json', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryFile', models.FilePathField(null=True)),
                ('cityFile', models.FilePathField(null=True)),
                ('hotelFile', models.FilePathField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('sourceId', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=64, null=True)),
                ('tosId', models.IntegerField(null=True)),
                ('cityId', models.CharField(max_length=32)),
                ('name_en', models.CharField(max_length=128)),
                ('name_cn', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('zipCode', models.CharField(max_length=32, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('geohash8', models.CharField(max_length=16, null=True)),
                ('starRating', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=128, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('sourceId', models.IntegerField(unique=True)),
                ('cityId', models.CharField(max_length=32, null=True)),
                ('countryCode', models.CharField(max_length=16, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('json', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='hotelupdate',
            index_together=set([('source', 'cityId')]),
        ),
        migrations.AlterIndexTogether(
            name='destination',
            index_together=set([('inactive', 'tosId')]),
        ),
    ]
