# Generated by Django 2.0.2 on 2018-04-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DidaBedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField(unique=True)),
                ('defaultOccupancy', models.IntegerField()),
                ('name_cn', models.CharField(default='', max_length=64)),
                ('name_en', models.CharField(default='', max_length=64)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DidaBreakfastType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField(unique=True)),
                ('name_cn', models.CharField(default='', max_length=64)),
                ('name_en', models.CharField(default='', max_length=64)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DidaCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceId', models.CharField(max_length=10, unique=True)),
                ('name_cn', models.CharField(default='', max_length=128)),
                ('name_en', models.CharField(default='', max_length=64)),
                ('destId', models.IntegerField(null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DidaCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceId', models.CharField(max_length=10, unique=True)),
                ('name_cn', models.CharField(default='', max_length=64)),
                ('name_en', models.CharField(default='', max_length=64)),
                ('destId', models.IntegerField(null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DidaHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceId', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('zipCode', models.CharField(max_length=32, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geohash8', models.CharField(db_index=True, max_length=16)),
                ('starRating', models.IntegerField()),
                ('telephone', models.CharField(max_length=32, null=True)),
                ('amenity', models.TextField(null=True)),
                ('rooms', models.TextField(null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='Hotel_Supplier.DidaCity')),
            ],
        ),
        migrations.CreateModel(
            name='DidaPoiHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poiId', models.IntegerField(db_index=True)),
                ('public', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Hotel_Supplier.DidaHotel')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='didacountry',
            index_together={('inactive', 'destId')},
        ),
        migrations.AddField(
            model_name='didacity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='Hotel_Supplier.DidaCountry'),
        ),
        migrations.AlterUniqueTogether(
            name='didapoihotel',
            unique_together={('poiId', 'hotel')},
        ),
        migrations.AlterIndexTogether(
            name='didacity',
            index_together={('inactive', 'destId')},
        ),
    ]
